### ISSUE TITLE
Sometimes quiting shows errors in async callback

### ISSUE THREAD

**Issue by jsim2010** [jsim2010/papyr#11]

**Comment by jsim2010** [comment]
Unable to reproduce this issue at current time.

**Comment by jsim2010** [comment]
PipeError(-4047, 'broken pipe')
Traceback (most recent call last):

  File "Python\Python36-32\lib\site-packages\neovim\api\nvim.py", line 217, in command
    return self.request('nvim_command', string, **kwargs)

  File "Python\Python36-32\lib\site-packages\neovim\api\nvim.py", line 130, in request
    res = self._session.request(name, *args, **kwargs)

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\session.py", line 88, in request
    v = self._yielding_request(method, args)

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\session.py", line 151, in _yielding_request
    self._async_session.request(method, args, response_cb)

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\async_session.py", line 44, in request
    self._msgpack_stream.send([0, request_id, method, args])

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\msgpack_stream.py", line 35, in send
    self._event_loop.send(self._packer.pack(msg))

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 114, in send
    self._send(data)

  File "Python\Python36-32\lib\site-packages\neovim\msgpack_rpc\event_loop\uv.py", line 92, in _send
    self._write_stream.write(data, self._on_write)

pyuv._cpyuv.error.PipeError: (-4047, 'broken pipe')

the call was requested at
  File "Python\Python36-32\lib\site-packages\papyr-0.1.0.dev0-py3.6.egg\papyr\ui\__init__.py", line 125, in mode_change
    self.main.cursor.mode_index = mode_idx
  File "Python\Python36-32\lib\site-packages\papyr-0.1.0.dev0-py3.6.egg\papyr\ui\cursor.py", line 189, in mode_index
    SEND_QUERY("cursor_highlight", "nvim_get_hl_by_id(%d, 1)" % hl_id)
  File "Python\Python36-32\lib\site-packages\papyr-0.1.0.dev0-py3.6.egg\papyr\nvim.py", line 122, in send_query
    query))
  File "Python\Python36-32\lib\site-packages\papyr-0.1.0.dev0-py3.6.egg\papyr\nvim.py", line 90, in _send
    self.nvim_instance.async_call(function, *args)

**Comment by jsim2010** [comment]
Believe this was resolved between switching to `request (async_=True)` and moving all functionality to tkinter main thread.
